export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SSUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
export const GOOGLE_REDIRECT = 'GOOGLE_REDIRECT';
